apiVersion: v1
kind: PersistentVolume
metadata:
  name: alpha-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: manual
  hostPath:
    path: /var/lib/mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpha-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: alpha-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alpha-db-statefulset
spec:
  selector:
    matchLabels:
      app: alpha-db
  serviceName: alpha-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: alpha-db
    spec:
      serviceAccountName: api-sa
      containers:
        - name: alpha-db
          image: mysql:8.0.31
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: alpha-db-pvc